(()=>{
const root=document.documentElement,reduce=matchMedia('(prefers-reduced-motion: reduce)'),toggle=document.querySelector('#motion-toggle');let paused=reduce.matches;
function syncMotion(){root.classList.toggle('motion-paused',paused);toggle.setAttribute('aria-pressed',String(paused));toggle.innerHTML=paused?'Play motion <span>▷</span>':'Pause motion <span>Ⅱ</span>';if(paused)document.querySelectorAll('.floating-food').forEach(el=>el.style.setProperty('--parallax','0px'))}
syncMotion();toggle.addEventListener('click',()=>{paused=!paused;syncMotion()});reduce.addEventListener('change',()=>{paused=reduce.matches;syncMotion()});
if('IntersectionObserver' in window){root.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -20px 0px'});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
const hero=document.querySelector('.hero'),foods=[...document.querySelectorAll('[data-depth]')];let queued=false;function parallax(){queued=false;if(paused||reduce.matches||matchMedia('(max-width: 900px)').matches)return;const y=Math.min(scrollY,hero.offsetHeight);foods.forEach(el=>el.style.setProperty('--parallax',`${y*Number(el.dataset.depth)}px`))}addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(parallax)}},{passive:true});
const track=document.querySelector('#products'),prev=document.querySelector('#menu-prev'),next=document.querySelector('#menu-next');function syncCarousel(){const max=track.scrollWidth-track.clientWidth,position=Math.abs(track.scrollLeft);prev.disabled=position<5;next.disabled=position>=max-5;document.querySelector('#menu-position').textContent=max>5?'Swipe to find your bite':'All bites, right here'}
function move(direction){track.scrollBy({left:direction*(track.clientWidth*.85),behavior:paused||reduce.matches?'instant':'smooth'})}prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));track.addEventListener('scroll',syncCarousel,{passive:true});track.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}});new ResizeObserver(syncCarousel).observe(track);new MutationObserver(()=>{track.scrollLeft=0;syncCarousel()}).observe(track,{childList:true});syncCarousel();
const ingredients={smash:{number:'01 / THE SMASH',title:'HOT GRIDDLE.<br>CRISPY EDGES.',text:'Smashed onto a hot griddle for a deeply browned crust and a juicy center. That is where the flavor starts.'},cheese:{number:'02 / THE CHEDDAR',title:'CHEDDAR MELTS.<br>IT ALL CLICKS.',text:'Cheddar meets the patty while it is still sizzling, melting over the edges and into every bite.'},bun:{number:'03 / THE BRIOCHE',title:'SOFT BRIOCHE.<br>TOASTED RIGHT.',text:'Soft brioche, toasted on the inside. Made to hold the sauce and keep every bite together.'}};
const tabs=[...document.querySelectorAll('[data-ingredient]')],panel=document.querySelector('#ingredient-panel');function selectTab(button){const data=ingredients[button.dataset.ingredient];tabs.forEach(t=>{const active=t===button;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1});panel.setAttribute('aria-labelledby',button.id);panel.innerHTML=`<span class="ingredient-number">${data.number}</span><h3>${data.title}</h3><p>${data.text}</p>`;if(!paused&&!reduce.matches)panel.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:'ease-out'})}tabs.forEach((button,i)=>{button.addEventListener('click',()=>selectTab(button));button.addEventListener('keydown',e=>{let index;if(e.key==='ArrowRight')index=(i+1)%tabs.length;else if(e.key==='ArrowLeft')index=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=tabs.length-1;else return;e.preventDefault();tabs[index].focus();selectTab(tabs[index])})});
})();
